services:
  postgres:
    image: "postgres:14.0"
    container_name: postgres
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_service
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
